name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Configurar Envs
        run: echo '${{ secrets.FIREBASE_CREDENTIALS }}' > src/boot/firebase.js

      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: stockset-1ac85
