name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Atualizando keys em firebase.js
        run: |
          sed -i "s/'FIREBASE_APIKEY'/'${{ secrets.FIREBASE_APIKEY }}'/" src/boot/firebase.js
          sed -i "s/'FIREBASE_PROJECTID'/'${{ secrets.FIREBASE_PROJECTID }}'/" src/boot/firebase.js
          sed -i "s/'FIREBASE_STORAGE'/'${{ secrets.FIREBASE_STORAGE }}'/" src/boot/firebase.js
          sed -i "s/'FIREBASE_APPID'/'${{ secrets.FIREBASE_APPID }}'/" src/boot/firebase.js

      - name: Install dependencies
        run: yarn

      - name: Atualizar browsers
        run: npx update-browserslist-db@latest

      - name: Build project
        run: yarn quasar build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: stockset-1ac85
